/**
 * QuantiModo
 * QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do). 
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/// <reference path="api.d.ts" />

/* tslint:disable:no-unused-variable member-ordering */

namespace API.Client {
    'use strict';

    export class PairsApi {
        protected basePath = 'https://app.quantimo.do/api';
        public defaultHeaders : any = {};

        static $inject: string[] = ['$http', '$httpParamSerializer', 'basePath'];

        constructor(protected $http: ng.IHttpService, protected $httpParamSerializer?: (d: any) => any, basePath?: string) {
            if (basePath !== undefined) {
                this.basePath = basePath;
            }
        }

        private extendObj<T1,T2>(objA: T1, objB: T2) {
            for(let key in objB){
                if(objB.hasOwnProperty(key)){
                    objA[key] = objB[key];
                }
            }
            return <T1&T2>objA;
        }

        /**
         * Get pairs
         * Pairs cause measurements with effect measurements grouped over the duration of action after the onset delay.
         * @param cause Original variable name for the explanatory or independent variable
         * @param effect Original variable name for the outcome or dependent variable
         * @param accessToken User&#39;s OAuth2 access token
         * @param userId User&#39;s id
         * @param causeSource Name of data source that the cause measurements should come from
         * @param causeUnit Abbreviated name for the unit cause measurements to be returned in
         * @param delay The amount of time in seconds that elapses after the predictor/stimulus event before the outcome as perceived by a self-tracker is known as the “onset delay”. For example, the “onset delay” between the time a person takes an aspirin (predictor/stimulus event) and the time a person perceives a change in their headache severity (outcome) is approximately 30 minutes.
         * @param duration The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable’s value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay.
         * @param effectSource Name of data source that the effectmeasurements should come from
         * @param effectUnit Abbreviated name for the unit effect measurements to be returned in
         * @param endTime The most recent date (in epoch time) for which we should return measurements
         * @param startTime The earliest date (in epoch time) for which we should return measurements
         * @param limit The LIMIT is used to limit the number of results returned. So if you have 1000 results, but only want to the first 10, you would set this to 10 and offset to 0.
         * @param offset Since the maximum limit is 200 records, to get more than that you&#39;ll have to make multiple API calls and page through the results. To retrieve all the data, you can iterate through data by using the &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  For example, if you want to retrieve data from 61-80 then you can use a query with the following parameters, &#x60;imit&#x3D;20&amp;offset&#x3D;60&#x60;.
         * @param sort Sort by given field. If the field is prefixed with &#x60;-, it will sort in descending order.
         */
        public v1PairsCsvGet (cause: string, effect: string, accessToken?: string, userId?: number, causeSource?: string, causeUnit?: string, delay?: string, duration?: string, effectSource?: string, effectUnit?: string, endTime?: string, startTime?: string, limit?: number, offset?: number, sort?: number, extraHttpRequestParams?: any ) : ng.IHttpPromise<Array<Pairs>> {
            const localVarPath = this.basePath + '/v1/pairsCsv';

            let queryParameters: any = {};
            let headerParams: any = this.extendObj({}, this.defaultHeaders);
            // verify required parameter 'cause' is not null or undefined
            if (cause === null || cause === undefined) {
                throw new Error('Required parameter cause was null or undefined when calling v1PairsCsvGet.');
            }
            // verify required parameter 'effect' is not null or undefined
            if (effect === null || effect === undefined) {
                throw new Error('Required parameter effect was null or undefined when calling v1PairsCsvGet.');
            }
            if (accessToken !== undefined) {
                queryParameters['access_token'] = accessToken;
            }

            if (userId !== undefined) {
                queryParameters['userId'] = userId;
            }

            if (cause !== undefined) {
                queryParameters['cause'] = cause;
            }

            if (causeSource !== undefined) {
                queryParameters['causeSource'] = causeSource;
            }

            if (causeUnit !== undefined) {
                queryParameters['causeUnit'] = causeUnit;
            }

            if (delay !== undefined) {
                queryParameters['delay'] = delay;
            }

            if (duration !== undefined) {
                queryParameters['duration'] = duration;
            }

            if (effect !== undefined) {
                queryParameters['effect'] = effect;
            }

            if (effectSource !== undefined) {
                queryParameters['effectSource'] = effectSource;
            }

            if (effectUnit !== undefined) {
                queryParameters['effectUnit'] = effectUnit;
            }

            if (endTime !== undefined) {
                queryParameters['endTime'] = endTime;
            }

            if (startTime !== undefined) {
                queryParameters['startTime'] = startTime;
            }

            if (limit !== undefined) {
                queryParameters['limit'] = limit;
            }

            if (offset !== undefined) {
                queryParameters['offset'] = offset;
            }

            if (sort !== undefined) {
                queryParameters['sort'] = sort;
            }

            let httpRequestParams: any = {
                method: 'GET',
                url: localVarPath,
                json: true,
                                                params: queryParameters,
                headers: headerParams
            };

            if (extraHttpRequestParams) {
                httpRequestParams = this.extendObj(httpRequestParams, extraHttpRequestParams);
            }

            return this.$http(httpRequestParams);
        }
        /**
         * Get pairs
         * Pairs cause measurements with effect measurements grouped over the duration of action after the onset delay.
         * @param cause Original variable name for the explanatory or independent variable
         * @param effect Original variable name for the outcome or dependent variable
         * @param accessToken User&#39;s OAuth2 access token
         * @param userId User&#39;s id
         * @param causeSource Name of data source that the cause measurements should come from
         * @param causeUnit Abbreviated name for the unit cause measurements to be returned in
         * @param delay The amount of time in seconds that elapses after the predictor/stimulus event before the outcome as perceived by a self-tracker is known as the “onset delay”. For example, the “onset delay” between the time a person takes an aspirin (predictor/stimulus event) and the time a person perceives a change in their headache severity (outcome) is approximately 30 minutes.
         * @param duration The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable’s value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay.
         * @param effectSource Name of data source that the effectmeasurements should come from
         * @param effectUnit Abbreviated name for the unit effect measurements to be returned in
         * @param endTime The most recent date (in epoch time) for which we should return measurements
         * @param startTime The earliest date (in epoch time) for which we should return measurements
         * @param limit The LIMIT is used to limit the number of results returned. So if you have 1000 results, but only want to the first 10, you would set this to 10 and offset to 0.
         * @param offset Since the maximum limit is 200 records, to get more than that you&#39;ll have to make multiple API calls and page through the results. To retrieve all the data, you can iterate through data by using the &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  For example, if you want to retrieve data from 61-80 then you can use a query with the following parameters, &#x60;imit&#x3D;20&amp;offset&#x3D;60&#x60;.
         * @param sort Sort by given field. If the field is prefixed with &#x60;-, it will sort in descending order.
         */
        public v1PairsGet (cause: string, effect: string, accessToken?: string, userId?: number, causeSource?: string, causeUnit?: string, delay?: string, duration?: string, effectSource?: string, effectUnit?: string, endTime?: string, startTime?: string, limit?: number, offset?: number, sort?: number, extraHttpRequestParams?: any ) : ng.IHttpPromise<Array<Pairs>> {
            const localVarPath = this.basePath + '/v1/pairs';

            let queryParameters: any = {};
            let headerParams: any = this.extendObj({}, this.defaultHeaders);
            // verify required parameter 'cause' is not null or undefined
            if (cause === null || cause === undefined) {
                throw new Error('Required parameter cause was null or undefined when calling v1PairsGet.');
            }
            // verify required parameter 'effect' is not null or undefined
            if (effect === null || effect === undefined) {
                throw new Error('Required parameter effect was null or undefined when calling v1PairsGet.');
            }
            if (accessToken !== undefined) {
                queryParameters['access_token'] = accessToken;
            }

            if (userId !== undefined) {
                queryParameters['userId'] = userId;
            }

            if (cause !== undefined) {
                queryParameters['cause'] = cause;
            }

            if (causeSource !== undefined) {
                queryParameters['causeSource'] = causeSource;
            }

            if (causeUnit !== undefined) {
                queryParameters['causeUnit'] = causeUnit;
            }

            if (delay !== undefined) {
                queryParameters['delay'] = delay;
            }

            if (duration !== undefined) {
                queryParameters['duration'] = duration;
            }

            if (effect !== undefined) {
                queryParameters['effect'] = effect;
            }

            if (effectSource !== undefined) {
                queryParameters['effectSource'] = effectSource;
            }

            if (effectUnit !== undefined) {
                queryParameters['effectUnit'] = effectUnit;
            }

            if (endTime !== undefined) {
                queryParameters['endTime'] = endTime;
            }

            if (startTime !== undefined) {
                queryParameters['startTime'] = startTime;
            }

            if (limit !== undefined) {
                queryParameters['limit'] = limit;
            }

            if (offset !== undefined) {
                queryParameters['offset'] = offset;
            }

            if (sort !== undefined) {
                queryParameters['sort'] = sort;
            }

            let httpRequestParams: any = {
                method: 'GET',
                url: localVarPath,
                json: true,
                                                params: queryParameters,
                headers: headerParams
            };

            if (extraHttpRequestParams) {
                httpRequestParams = this.extendObj(httpRequestParams, extraHttpRequestParams);
            }

            return this.$http(httpRequestParams);
        }
    }
}
