export * from './analytics.service';
import { AnalyticsService } from './analytics.service';
export * from './appSettings.service';
import { AppSettingsService } from './appSettings.service';
export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './connectors.service';
import { ConnectorsService } from './connectors.service';
export * from './measurements.service';
import { MeasurementsService } from './measurements.service';
export * from './notifications.service';
import { NotificationsService } from './notifications.service';
export * from './reminders.service';
import { RemindersService } from './reminders.service';
export * from './shares.service';
import { SharesService } from './shares.service';
export * from './studies.service';
import { StudiesService } from './studies.service';
export * from './units.service';
import { UnitsService } from './units.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './variables.service';
import { VariablesService } from './variables.service';
export const APIS = [AnalyticsService, AppSettingsService, AuthenticationService, ConnectorsService, MeasurementsService, NotificationsService, RemindersService, SharesService, StudiesService, UnitsService, UserService, VariablesService];
