/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface Button {
    /**
     * Ex: https://local.quantimo.do
     */
    link: string;
    /**
     * Ex: Connect
     */
    text: string;
    /**
     * Ex: ion-refresh
     */
    ionIcon?: string;
    /**
     * Ex: #f2f2f2
     */
    color?: string;
    /**
     * Ex: connect
     */
    additionalInformation?: string;
}
