/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface DataSource {
    /**
     * Ex: true
     */
    affiliate: boolean;
    /**
     * Ex: ba7d0c12432650e23b3ce924ae2d21e2ff59e7e4e28650759633700af7ed0a30
     */
    connectorClientId: string;
    /**
     * Ex: Foods
     */
    defaultVariableCategoryName: string;
    /**
     * Ex: QuantiModo
     */
    displayName: string;
    /**
     * Ex: 0
     */
    enabled: number;
    /**
     * Ex: https://quantimo.do
     */
    getItUrl: string;
    /**
     * Ex: 72
     */
    id: number;
    /**
     * Ex: https://quantimodo.quantimo.do/ionic/Modo/www/img/logos/quantimodo-logo-qm-rainbow-200-200.png
     */
    image: string;
    /**
     * Ex: <a href=\"https://quantimo.do\"><img id=\"quantimodo_image\" title=\"QuantiModo\" src=\"https://quantimodo.quantimo.do/ionic/Modo/www/img/logos/quantimodo-logo-qm-rainbow-200-200.png\" alt=\"QuantiModo\"></a>
     */
    imageHtml: string;
    /**
     * Ex: <a href=\"https://quantimo.do\">QuantiModo</a>
     */
    linkedDisplayNameHtml: string;
    /**
     * Ex: QuantiModo is a Chrome extension, Android app, iOS app, and web app that allows you to easily track mood, symptoms, or any outcome you want to optimize in a fraction of a second.  You can also import your data from over 30 other apps and devices like Fitbit, Rescuetime, Jawbone Up, Withings, Facebook, Github, Google Calendar, Runkeeper, MoodPanda, Slice, Google Fit, and more.  QuantiModo then analyzes your data to identify which hidden factors are most likely to be influencing your mood or symptoms and their optimal daily values.
     */
    longDescription: string;
    /**
     * Ex: quantimodo
     */
    name: string;
    /**
     * Ex: Tracks anything
     */
    shortDescription: string;
}
