/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface PostCorrelation {
    /**
     * Cause variable name
     */
    causeVariableName: string;
    /**
     * Correlation value
     */
    correlation: number;
    /**
     * Effect variable name
     */
    effectVariableName: string;
    /**
     * Vote: 0 or 1
     */
    vote?: number;
}
