/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Correlation } from './correlation';
import { ParticipantInstruction } from './participantInstruction';
import { StudyCharts } from './studyCharts';
import { StudyHtml } from './studyHtml';
import { StudyImages } from './studyImages';
import { StudyLinks } from './studyLinks';
import { StudyText } from './studyText';
import { Variable } from './variable';


export interface Study {
    /**
     * Ex: population, cohort, or individual
     */
    type: string;
    /**
     * The user id of the principal investigator or subject if an individual studies
     */
    userId?: string;
    /**
     * ID of the cohort study which is necessary to allow participants to join
     */
    studyId?: string;
    causeVariable?: Variable;
    studyCharts?: StudyCharts;
    effectVariable?: Variable;
    participantInstructions?: ParticipantInstruction;
    statistics?: Correlation;
    studyHtml?: StudyHtml;
    studyImages?: StudyImages;
    studyLinks?: StudyLinks;
    studyText?: StudyText;
}
