/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface VariableCategory {
    /**
     * Ex: mood
     */
    appType?: string;
    /**
     * Ex: false
     */
    causeOnly?: boolean;
    /**
     * Ex: MEAN
     */
    combinationOperation?: string;
    /**
     * UTC ISO 8601 YYYY-MM-DDThh:mm:ss
     */
    createdTime?: string;
    /**
     * Ex: /5
     */
    unitAbbreviatedName?: string;
    /**
     * Ex: 10
     */
    unitId?: number;
    /**
     * Ex: 86400
     */
    durationOfAction?: number;
    /**
     * Ex: -1
     */
    fillingValue?: number;
    /**
     * Ex: What emotion do you want to rate?
     */
    helpText?: string;
    /**
     * Ex: 1
     */
    id?: number;
    /**
     * Ex: https://maxcdn.icons8.com/Color/PNG/96/Cinema/theatre_mask-96.png
     */
    imageUrl?: string;
    /**
     * Ex: ion-happy-outline
     */
    ionIcon?: string;
    /**
     * Ex: true
     */
    manualTracking?: boolean;
    /**
     * Ex: 
     */
    maximumAllowedValue?: string;
    /**
     * Ex: rating
     */
    measurementSynonymSingularLowercase?: string;
    /**
     * Ex: 
     */
    minimumAllowedValue?: string;
    /**
     * Ex: Do you have any emotions that fluctuate regularly?  If so, add them so I can try to determine which factors are influencing them.
     */
    moreInfo?: string;
    /**
     * Category name
     */
    name: string;
    /**
     * Ex: 0
     */
    onsetDelay?: number;
    /**
     * Ex: true
     */
    outcome?: boolean;
    /**
     * Ex: img/variable_categories/emotions.png
     */
    pngPath?: string;
    /**
     * Ex: https://quantimodo.quantimo.do/ionic/Modo/www/img/variable_categories/emotions.png
     */
    pngUrl?: string;
    /**
     * Ex: true
     */
    public?: boolean;
    /**
     * Ex: img/variable_categories/emotions.svg
     */
    svgPath?: string;
    /**
     * Ex: https://quantimodo.quantimo.do/ionic/Modo/www/img/variable_categories/emotions.svg
     */
    svgUrl?: string;
    /**
     * Ex: 1
     */
    updated?: number;
    /**
     * UTC ISO 8601 YYYY-MM-DDThh:mm:ss
     */
    updatedTime?: string;
    /**
     * Ex: Emotions
     */
    variableCategoryName?: string;
    /**
     * Ex: Emotion
     */
    variableCategoryNameSingular?: string;
}
